# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ecred_MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1113, 637)
        MainWindow.setStyleSheet("background-color: rgb(42, 38, 62);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.TopMenuWidget = QtWidgets.QWidget(self.widget)
        self.TopMenuWidget.setObjectName("TopMenuWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.TopMenuWidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.SideBarButton = QtWidgets.QPushButton(self.TopMenuWidget)
        self.SideBarButton.setStyleSheet("QPushButton{\n"
"    background-image: url(:/LavendarIcons/Lavendarfeather/sidebar.svg);\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"    background-color:rgb(59, 56, 84);\n"
"    \n"
"    border-style: none;\n"
"    border-color: rgb(59, 56, 84);\n"
"    border-radius: 8px; /* Set your desired border radius */\n"
"\n"
"    color:white;\n"
"    width:65;\n"
"    height:45;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(42, 38, 62);\n"
"    border-style: outset;\n"
"    border-width: 0.5px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(67, 42, 73);\n"
"    border-style: none;\n"
"}")
        self.SideBarButton.setText("")
        self.SideBarButton.setIconSize(QtCore.QSize(23, 23))
        self.SideBarButton.setObjectName("SideBarButton")
        self.horizontalLayout_2.addWidget(self.SideBarButton)
        self.LoginButton = QtWidgets.QPushButton(self.TopMenuWidget)
        self.LoginButton.setStyleSheet("QPushButton{\n"
"    background-image: url(:/LavendarIcons/Lavendarfeather/log-in.svg);\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"    background-color:rgb(59, 56, 84);\n"
"    \n"
"    border-style: none;\n"
"    border-color: rgb(59, 56, 84);\n"
"    border-radius: 8px; /* Set your desired border radius */\n"
"\n"
"    color:white;\n"
"    width:65;\n"
"    height:45;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(42, 38, 62);\n"
"    border-style: outset;\n"
"    border-width: 0.5px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(67, 42, 73);\n"
"    border-style: none;\n"
"}")
        self.LoginButton.setText("")
        self.LoginButton.setObjectName("LoginButton")
        self.horizontalLayout_2.addWidget(self.LoginButton)
        self.SaveSQLButton = QtWidgets.QPushButton(self.TopMenuWidget)
        self.SaveSQLButton.setStyleSheet("QPushButton{\n"
"    background-image: url(:/LavendarIcons/Lavendarfeather/save.svg);\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"    background-color:rgb(59, 56, 84);\n"
"    \n"
"    border-style: none;\n"
"    border-color: rgb(59, 56, 84);\n"
"    border-radius: 8px; /* Set your desired border radius */\n"
"\n"
"    color:white;\n"
"    width:65;\n"
"    height:45;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(42, 38, 62);\n"
"    border-style: outset;\n"
"    border-width: 0.5px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(67, 42, 73);\n"
"    border-style: none;\n"
"}")
        self.SaveSQLButton.setText("")
        self.SaveSQLButton.setObjectName("SaveSQLButton")
        self.horizontalLayout_2.addWidget(self.SaveSQLButton)
        self.ReportsWindowButton = QtWidgets.QPushButton(self.TopMenuWidget)
        self.ReportsWindowButton.setStyleSheet("QPushButton{\n"
"    background-image: url(:/LavendarIcons/Lavendarfeather/layers.svg);\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"    background-color:rgb(59, 56, 84);\n"
"    \n"
"    border-style: none;\n"
"    border-color: rgb(59, 56, 84);\n"
"    border-radius: 8px; /* Set your desired border radius */\n"
"\n"
"    color:white;\n"
"    width:65;\n"
"    height:45;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(42, 38, 62);\n"
"    border-style: outset;\n"
"    border-width: 0.5px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(67, 42, 73);\n"
"    border-style: none;\n"
"}")
        self.ReportsWindowButton.setText("")
        self.ReportsWindowButton.setObjectName("ReportsWindowButton")
        self.horizontalLayout_2.addWidget(self.ReportsWindowButton)
        self.QueryRunButton = QtWidgets.QPushButton(self.TopMenuWidget)
        self.QueryRunButton.setStyleSheet("QPushButton{\n"
"    background-image: url(:/LavendarIcons/Lavendarfeather/play.svg);\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"    background-color:rgb(59, 56, 84);\n"
"    \n"
"    border-style: none;\n"
"    border-color: rgb(59, 56, 84);\n"
"    border-radius: 8px; /* Set your desired border radius */\n"
"\n"
"    color:white;\n"
"    width:65;\n"
"    height:45;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(42, 38, 62);\n"
"    border-style: outset;\n"
"    border-width: 0.5px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(67, 42, 73);\n"
"    border-style: none;\n"
"}")
        self.QueryRunButton.setText("")
        self.QueryRunButton.setObjectName("QueryRunButton")
        self.horizontalLayout_2.addWidget(self.QueryRunButton)
        self.QueryAbortButton = QtWidgets.QPushButton(self.TopMenuWidget)
        self.QueryAbortButton.setStyleSheet("QPushButton{\n"
"    background-image: url(:/LavendarIcons/Lavendarfeather/x.svg);\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"    background-color:rgb(59, 56, 84);\n"
"    \n"
"    border-style: none;\n"
"    border-color: rgb(59, 56, 84);\n"
"    border-radius: 8px; /* Set your desired border radius */\n"
"\n"
"    color:white;\n"
"    width:65;\n"
"    height:45;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(42, 38, 62);\n"
"    border-style: outset;\n"
"    border-width: 0.5px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(67, 42, 73);\n"
"    border-style: none;\n"
"}")
        self.QueryAbortButton.setText("")
        self.QueryAbortButton.setObjectName("QueryAbortButton")
        self.horizontalLayout_2.addWidget(self.QueryAbortButton)
        spacerItem = QtWidgets.QSpacerItem(342, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.ThemeChangeButton = QtWidgets.QPushButton(self.TopMenuWidget)
        self.ThemeChangeButton.setStyleSheet("QPushButton{\n"
"    background-image: url(:/LavendarIcons/Lavendarfeather/sun.svg);\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"    background-color:rgb(59, 56, 84);\n"
"    \n"
"    border-style: none;\n"
"    border-color: rgb(59, 56, 84);\n"
"    border-radius: 8px; /* Set your desired border radius */\n"
"\n"
"    color:white;\n"
"    width:65;\n"
"    height:45;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(42, 38, 62);\n"
"    border-style: outset;\n"
"    border-width: 0.5px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(67, 42, 73);\n"
"    border-style: none;\n"
"}")
        self.ThemeChangeButton.setText("")
        self.ThemeChangeButton.setObjectName("ThemeChangeButton")
        self.horizontalLayout_2.addWidget(self.ThemeChangeButton)
        self.NotificationBellButton = QtWidgets.QPushButton(self.TopMenuWidget)
        self.NotificationBellButton.setStyleSheet("QPushButton{\n"
"    background-image: url(:/LavendarIcons/Lavendarfeather/bell.svg);\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"    background-color:rgb(59, 56, 84);\n"
"    \n"
"    border-style: none;\n"
"    border-color: rgb(59, 56, 84);\n"
"    border-radius: 8px; /* Set your desired border radius */\n"
"\n"
"    color:white;\n"
"    width:65;\n"
"    height:45;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(42, 38, 62);\n"
"    border-style: outset;\n"
"    border-width: 0.5px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(67, 42, 73);\n"
"    border-style: none;\n"
"}")
        self.NotificationBellButton.setText("")
        self.NotificationBellButton.setObjectName("NotificationBellButton")
        self.horizontalLayout_2.addWidget(self.NotificationBellButton)
        self.LogoutButton = QtWidgets.QPushButton(self.TopMenuWidget)
        self.LogoutButton.setStyleSheet("QPushButton{\n"
"    background-image: url(:/LavendarIcons/Lavendarfeather/log-out.svg);\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"    background-color:rgb(59, 56, 84);\n"
"    \n"
"    border-style: none;\n"
"    border-color: rgb(59, 56, 84);\n"
"    border-radius: 8px; /* Set your desired border radius */\n"
"\n"
"    color:rgb(153, 148, 186);\n"
"    font-family: Arial;\n"
"    font-size: 18px; /* Set your desired font size */\n"
"    width:65;\n"
"    height:45;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(42, 38, 62);\n"
"    border-style: outset;\n"
"    border-width: 0.5px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(67, 42, 73);\n"
"    border-style: none;\n"
"}")
        self.LogoutButton.setText("")
        self.LogoutButton.setObjectName("LogoutButton")
        self.horizontalLayout_2.addWidget(self.LogoutButton)
        self.HelpButton = QtWidgets.QPushButton(self.TopMenuWidget)
        self.HelpButton.setStyleSheet("QPushButton{\n"
"    background-image: url(:/LavendarIcons/Lavendarfeather/help-circle.svg);\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"    background-color:rgb(59, 56, 84);\n"
"    \n"
"    border-style: none;\n"
"    border-color: rgb(59, 56, 84);\n"
"    border-radius: 8px; /* Set your desired border radius */\n"
"\n"
"    color:white;\n"
"    width:65;\n"
"    height:45;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(42, 38, 62);\n"
"    border-style: outset;\n"
"    border-width: 0.5px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(67, 42, 73);\n"
"    border-style: none;\n"
"}")
        self.HelpButton.setText("")
        self.HelpButton.setObjectName("HelpButton")
        self.horizontalLayout_2.addWidget(self.HelpButton)
        self.verticalLayout_2.addWidget(self.TopMenuWidget)
        self.BodyWidget = QtWidgets.QWidget(self.widget)
        self.BodyWidget.setObjectName("BodyWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.BodyWidget)
        self.horizontalLayout.setContentsMargins(-1, 13, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_2 = QtWidgets.QWidget(self.BodyWidget)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.toolBox = QtWidgets.QToolBox(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.toolBox.setFont(font)
        self.toolBox.setStyleSheet("QToolBox::tab {\n"
"    background-color: rgb(42, 38, 62); /* Set the background color of the tabs */\n"
"    color: rgb(238, 236, 255); /* Set the text color of the tabs */\n"
"    font-family: Arial;\n"
"    font-size: 15px; /* Set the font size of the tab labels */\n"
"    padding: 5px; /* Set the padding around the tab labels */\n"
"    \n"
"    border-style: outset;\n"
"    border-width: 0.5px;\n"
"    border-color: rgb(59, 56, 84);\n"
"    border-radius: 5px; /* Set your desired border radius */\n"
"}\n"
"\n"
"QToolBox::tab:hover {\n"
"     background-color: rgb(59, 56, 84); /* Set the background color of the tab on hover */\n"
"}\n"
"\n"
"QToolBox::tab:selected {\n"
"    background-color: rgb(147, 121, 182); /* Set the background color of the selected tab */\n"
"    color: rgb(238, 236, 255);\n"
"}")
        self.toolBox.setObjectName("toolBox")
        self.UtilitiesPage = QtWidgets.QWidget()
        self.UtilitiesPage.setGeometry(QtCore.QRect(0, 0, 190, 359))
        self.UtilitiesPage.setObjectName("UtilitiesPage")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.UtilitiesPage)
        self.verticalLayout_10.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.widget_14 = QtWidgets.QWidget(self.UtilitiesPage)
        self.widget_14.setStyleSheet("")
        self.widget_14.setObjectName("widget_14")
        self.formLayout = QtWidgets.QFormLayout(self.widget_14)
        self.formLayout.setContentsMargins(2, 2, 2, 2)
        self.formLayout.setObjectName("formLayout")
        self.DBLabel = QtWidgets.QLabel(self.widget_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DBLabel.sizePolicy().hasHeightForWidth())
        self.DBLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.DBLabel.setFont(font)
        self.DBLabel.setStyleSheet("QLabel{\n"
"    background-image: url(:/LavendarIcons/Lavendarfeather/database.svg);\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"    color: rgb(42, 38, 62);\n"
"    font-size:20px;\n"
"}")
        self.DBLabel.setObjectName("DBLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.DBLabel)
        self.DBComboBox = QtWidgets.QComboBox(self.widget_14)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        self.DBComboBox.setFont(font)
        self.DBComboBox.setStyleSheet("QComboBox {\n"
"    background-color: rgb(64, 58, 95); /* Set your desired background color */\n"
"    color: rgb(238, 236, 255);/* Set your desired text color */\n"
"    font-family: Arial;\n"
"    font-size: 15px; /* Set your desired font size */\n"
"    border-style: none;\n"
"    /*border: 1px solid #CCCCCC; Set your desired border style */\n"
"    border-radius: 5px; /* Set your desired border radius */\n"
"    padding: 5px; /* Set your desired padding */\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background-color: rgb(64, 58, 95); /* Set your desired background color */\n"
"    color: rgb(238, 236, 255);\n"
"    selection-background-color: rgb(147, 121, 182);\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    \n"
"    border: none;\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: right;\n"
"    width: 20px; /* Set the width of the dropdown arrow */\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(:/LavendarIcons/Lavendarfeather/chevron-down.svg); /* Set the image for the dropdown arrow */\n"
"    width: 20px; /* Set the width of the dropdown arrow image */\n"
"    height: 15px; /* Set the height of the dropdown arrow image */\n"
"}")
        self.DBComboBox.setObjectName("DBComboBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.DBComboBox)
        self.SchemaLabel = QtWidgets.QLabel(self.widget_14)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.SchemaLabel.setFont(font)
        self.SchemaLabel.setStyleSheet("QLabel{\n"
"    background-image: url(:/LavendarIcons/Lavendarfeather/trello.svg);\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"    color: rgb(42, 38, 62);\n"
"    font-size:20px;\n"
"}")
        self.SchemaLabel.setObjectName("SchemaLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.SchemaLabel)
        self.SchemaComboBox = QtWidgets.QComboBox(self.widget_14)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        self.SchemaComboBox.setFont(font)
        self.SchemaComboBox.setStyleSheet("QComboBox {\n"
"    background-color: rgb(64, 58, 95); /* Set your desired background color */\n"
"    color: rgb(238, 236, 255);/* Set your desired text color */\n"
"    font-family: Arial;\n"
"    font-size: 15px; /* Set your desired font size */\n"
"    border-style: none;\n"
"    /*border: 1px solid #CCCCCC; Set your desired border style */\n"
"    border-radius: 5px; /* Set your desired border radius */\n"
"    padding: 5px; /* Set your desired padding */\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background-color: rgb(64, 58, 95); /* Set your desired background color */\n"
"    color: rgb(238, 236, 255);\n"
"    selection-background-color: rgb(147, 121, 182);\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    \n"
"    border: none;\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: right;\n"
"    width: 20px; /* Set the width of the dropdown arrow */\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(:/LavendarIcons/Lavendarfeather/chevron-down.svg); /* Set the image for the dropdown arrow */\n"
"    width: 20px; /* Set the width of the dropdown arrow image */\n"
"    height: 15px; /* Set the height of the dropdown arrow image */\n"
"}")
        self.SchemaComboBox.setObjectName("SchemaComboBox")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.SchemaComboBox)
        self.TableLabel = QtWidgets.QLabel(self.widget_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TableLabel.sizePolicy().hasHeightForWidth())
        self.TableLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.TableLabel.setFont(font)
        self.TableLabel.setStyleSheet("QLabel{\n"
"    background-image: url(:/LavendarIcons/Lavendarfeather/table.svg);\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"    color: rgb(42, 38, 62);\n"
"    font-size:20px;\n"
"}")
        self.TableLabel.setObjectName("TableLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.TableLabel)
        self.TableComboBox = QtWidgets.QComboBox(self.widget_14)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        self.TableComboBox.setFont(font)
        self.TableComboBox.setStyleSheet("QComboBox {\n"
"    background-color: rgb(64, 58, 95); /* Set your desired background color */\n"
"    color: rgb(238, 236, 255);/* Set your desired text color */\n"
"    font-family: Arial;\n"
"    font-size: 15px; /* Set your desired font size */\n"
"    border-style: none;\n"
"    /*border: 1px solid #CCCCCC; Set your desired border style */\n"
"    border-radius: 5px; /* Set your desired border radius */\n"
"    padding: 5px; /* Set your desired padding */\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background-color: rgb(64, 58, 95); /* Set your desired background color */\n"
"    color: rgb(238, 236, 255);\n"
"    selection-background-color: rgb(147, 121, 182);\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    \n"
"    border: none;\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: right;\n"
"    width: 20px; /* Set the width of the dropdown arrow */\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(:/LavendarIcons/Lavendarfeather/chevron-down.svg); /* Set the image for the dropdown arrow */\n"
"    width: 20px; /* Set the width of the dropdown arrow image */\n"
"    height: 15px; /* Set the height of the dropdown arrow image */\n"
"}")
        self.TableComboBox.setObjectName("TableComboBox")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.TableComboBox)
        self.TopRowsLabel = QtWidgets.QLabel(self.widget_14)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        self.TopRowsLabel.setFont(font)
        self.TopRowsLabel.setStyleSheet("QLabel{\n"
"    color: rgb(238, 236, 255);/* Set your desired text color */\n"
"    font-family: Arial;\n"
"    font-size: 15px; /* Set your desired font size */\n"
"    }")
        self.TopRowsLabel.setObjectName("TopRowsLabel")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.TopRowsLabel)
        self.TopRowsLineEdit = QtWidgets.QLineEdit(self.widget_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TopRowsLineEdit.sizePolicy().hasHeightForWidth())
        self.TopRowsLineEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        self.TopRowsLineEdit.setFont(font)
        self.TopRowsLineEdit.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(53, 50, 76);/* Set your desired background color */\n"
"    color: rgb(238, 236, 255);/* Set your desired text color */\n"
"    font-family: Arial;\n"
"    font-size: 15px; /* Set your desired font size */\n"
"    border-style: none;\n"
"    /*border: 1px solid #CCCCCC;  Set your desired border style */\n"
"    border-radius: 5px; /* Set your desired border radius */\n"
"    padding: 5px; /* Set your desired padding */\n"
"    }")
        self.TopRowsLineEdit.setObjectName("TopRowsLineEdit")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.TopRowsLineEdit)
        self.NullAsLabel = QtWidgets.QLabel(self.widget_14)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        self.NullAsLabel.setFont(font)
        self.NullAsLabel.setStyleSheet("QLabel{\n"
"    color: rgb(238, 236, 255);/* Set your desired text color */\n"
"    font-family: Arial;\n"
"    font-size: 15px; /* Set your desired font size */\n"
"    }")
        self.NullAsLabel.setObjectName("NullAsLabel")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.NullAsLabel)
        self.NullAsLineEdit = QtWidgets.QLineEdit(self.widget_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NullAsLineEdit.sizePolicy().hasHeightForWidth())
        self.NullAsLineEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        self.NullAsLineEdit.setFont(font)
        self.NullAsLineEdit.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(53, 50, 76);/* Set your desired background color */\n"
"    color: rgb(238, 236, 255);/* Set your desired text color */\n"
"    font-family: Arial;\n"
"    font-size: 15px; /* Set your desired font size */\n"
"    border-style: none;\n"
"    /*border: 1px solid #CCCCCC;  Set your desired border style */\n"
"    border-radius: 5px; /* Set your desired border radius */\n"
"    padding: 5px; /* Set your desired padding */\n"
"    }")
        self.NullAsLineEdit.setText("")
        self.NullAsLineEdit.setObjectName("NullAsLineEdit")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.NullAsLineEdit)
        self.verticalLayout_10.addWidget(self.widget_14)
        self.toolBox.addItem(self.UtilitiesPage, "")
        self.StandardSQLPage = QtWidgets.QWidget()
        self.StandardSQLPage.setGeometry(QtCore.QRect(0, 0, 190, 359))
        self.StandardSQLPage.setObjectName("StandardSQLPage")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.StandardSQLPage)
        self.verticalLayout_11.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.widget_15 = QtWidgets.QWidget(self.StandardSQLPage)
        self.widget_15.setObjectName("widget_15")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.widget_15)
        self.verticalLayout_14.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.SearchStandardSQLLineEdit = QtWidgets.QLineEdit(self.widget_15)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        self.SearchStandardSQLLineEdit.setFont(font)
        self.SearchStandardSQLLineEdit.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(59, 56, 84);/* Set your desired background color */\n"
"    color: rgb(238, 236, 255);/* Set your desired text color */\n"
"    font-family: Arial;\n"
"    font-size: 15px; /* Set your desired font size */\n"
"    border-style: none;\n"
"    /*border: 1px solid #CCCCCC;  Set your desired border style */\n"
"    border-radius: 5px; /* Set your desired border radius */\n"
"    padding: 5px; /* Set your desired padding */\n"
"    }")
        self.SearchStandardSQLLineEdit.setText("")
        self.SearchStandardSQLLineEdit.setObjectName("SearchStandardSQLLineEdit")
        self.verticalLayout_14.addWidget(self.SearchStandardSQLLineEdit)
        self.StandardSQLListWidget = QtWidgets.QListWidget(self.widget_15)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.StandardSQLListWidget.setFont(font)
        self.StandardSQLListWidget.setStyleSheet("QListWidget{\n"
"    background-color: rgb(53, 50, 76);\n"
"    border-radius: 15px;\n"
"    }")
        self.StandardSQLListWidget.setObjectName("StandardSQLListWidget")
        self.verticalLayout_14.addWidget(self.StandardSQLListWidget)
        self.verticalLayout_11.addWidget(self.widget_15)
        self.toolBox.addItem(self.StandardSQLPage, "")
        self.UserSQLPage = QtWidgets.QWidget()
        self.UserSQLPage.setGeometry(QtCore.QRect(0, 0, 190, 359))
        self.UserSQLPage.setObjectName("UserSQLPage")
        self.verticalLayout_51 = QtWidgets.QVBoxLayout(self.UserSQLPage)
        self.verticalLayout_51.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_51.setObjectName("verticalLayout_51")
        self.widget_46 = QtWidgets.QWidget(self.UserSQLPage)
        self.widget_46.setObjectName("widget_46")
        self.verticalLayout_50 = QtWidgets.QVBoxLayout(self.widget_46)
        self.verticalLayout_50.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_50.setObjectName("verticalLayout_50")
        self.SearchUserSQLLineEdit = QtWidgets.QLineEdit(self.widget_46)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        self.SearchUserSQLLineEdit.setFont(font)
        self.SearchUserSQLLineEdit.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(59, 56, 84);/* Set your desired background color */\n"
"    color: rgb(238, 236, 255);/* Set your desired text color */\n"
"    font-family: Arial;\n"
"    font-size: 15px; /* Set your desired font size */\n"
"    border-style: none;\n"
"    /*border: 1px solid #CCCCCC;  Set your desired border style */\n"
"    border-radius: 5px; /* Set your desired border radius */\n"
"    padding: 5px; /* Set your desired padding */\n"
"    }")
        self.SearchUserSQLLineEdit.setText("")
        self.SearchUserSQLLineEdit.setObjectName("SearchUserSQLLineEdit")
        self.verticalLayout_50.addWidget(self.SearchUserSQLLineEdit)
        self.UserSQLListWidget = QtWidgets.QListWidget(self.widget_46)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.UserSQLListWidget.setFont(font)
        self.UserSQLListWidget.setStyleSheet("QListWidget{\n"
"    background-color: rgb(53, 50, 76);\n"
"    border-radius: 15px;\n"
"    }")
        self.UserSQLListWidget.setObjectName("UserSQLListWidget")
        self.verticalLayout_50.addWidget(self.UserSQLListWidget)
        self.verticalLayout_51.addWidget(self.widget_46)
        self.toolBox.addItem(self.UserSQLPage, "")
        self.PublicSQLPage = QtWidgets.QWidget()
        self.PublicSQLPage.setGeometry(QtCore.QRect(0, 0, 190, 359))
        self.PublicSQLPage.setObjectName("PublicSQLPage")
        self.verticalLayout_37 = QtWidgets.QVBoxLayout(self.PublicSQLPage)
        self.verticalLayout_37.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_37.setObjectName("verticalLayout_37")
        self.widget_38 = QtWidgets.QWidget(self.PublicSQLPage)
        self.widget_38.setObjectName("widget_38")
        self.verticalLayout_38 = QtWidgets.QVBoxLayout(self.widget_38)
        self.verticalLayout_38.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_38.setObjectName("verticalLayout_38")
        self.SearchPublicSQLLineEdit = QtWidgets.QLineEdit(self.widget_38)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        self.SearchPublicSQLLineEdit.setFont(font)
        self.SearchPublicSQLLineEdit.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(59, 56, 84);/* Set your desired background color */\n"
"    color: rgb(238, 236, 255);/* Set your desired text color */\n"
"    font-family: Arial;\n"
"    font-size: 15px; /* Set your desired font size */\n"
"    border-style: none;\n"
"    /*border: 1px solid #CCCCCC;  Set your desired border style */\n"
"    border-radius: 5px; /* Set your desired border radius */\n"
"    padding: 5px; /* Set your desired padding */\n"
"    }")
        self.SearchPublicSQLLineEdit.setText("")
        self.SearchPublicSQLLineEdit.setObjectName("SearchPublicSQLLineEdit")
        self.verticalLayout_38.addWidget(self.SearchPublicSQLLineEdit)
        self.PublicSQLTreeWidget = QtWidgets.QTreeWidget(self.widget_38)
        self.PublicSQLTreeWidget.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.PublicSQLTreeWidget.setStyleSheet("QTreeWidget {\n"
"    background-color: rgb(53, 50, 76);\n"
"    border-radius: 15px;\n"
"    color: rgb(238, 236, 255);/* Set your desired text color */\n"
"    font-family: Arial;\n"
"    font-size: 17px; /* Set your desired font size */\n"
"    padding: 5px; /* Set your desired padding */\n"
"    }\n"
"QHeaderView::section {\n"
"    background-color: rgb(53, 50, 76); /* Set your desired background color */\n"
"    color: rgb(238, 236, 255); /* Set your desired text color */\n"
"    font-family: Arial;\n"
"    font-weight:bold;\n"
"    font-size: 16px; /* Set your desired font size */\n"
"    border: none;\n"
"    padding: 5px; /* Set your desired padding */\n"
"    text-align: left; /* Set the alignment of the header text */\n"
"}")
        self.PublicSQLTreeWidget.setAnimated(False)
        self.PublicSQLTreeWidget.setObjectName("PublicSQLTreeWidget")
        self.verticalLayout_38.addWidget(self.PublicSQLTreeWidget)
        self.verticalLayout_37.addWidget(self.widget_38)
        self.toolBox.addItem(self.PublicSQLPage, "")
        self.verticalLayout_3.addWidget(self.toolBox)
        self.horizontalLayout.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(self.BodyWidget)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.ColumnsWidget = QtWidgets.QWidget(self.widget_3)
        self.ColumnsWidget.setObjectName("ColumnsWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.ColumnsWidget)
        self.verticalLayout_4.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.ColumnsLabel = QtWidgets.QLabel(self.ColumnsWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ColumnsLabel.sizePolicy().hasHeightForWidth())
        self.ColumnsLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.ColumnsLabel.setFont(font)
        self.ColumnsLabel.setStyleSheet("QLabel{\n"
"    background-color: rgb(42, 38, 62);\n"
"    color: rgb(238, 236, 255);/* Set your desired text color */\n"
"    font-family: Arial;\n"
"    font-size: 20px; /* Set your desired font size */\n"
"    font-weight: bold;\n"
"    }")
        self.ColumnsLabel.setObjectName("ColumnsLabel")
        self.verticalLayout_4.addWidget(self.ColumnsLabel)
        self.lineEdit = QtWidgets.QLineEdit(self.ColumnsWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(59, 56, 84);/* Set your desired background color */\n"
"    color: rgb(238, 236, 255);/* Set your desired text color */\n"
"    font-family: Arial;\n"
"    font-size: 15px; /* Set your desired font size */\n"
"    border-style: none;\n"
"    /*border: 1px solid #CCCCCC;  Set your desired border style */\n"
"    border-radius: 5px; /* Set your desired border radius */\n"
"    padding: 5px; /* Set your desired padding */\n"
"    }")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_4.addWidget(self.lineEdit)
        self.ColumnsTreeWidget = QtWidgets.QTreeWidget(self.ColumnsWidget)
        self.ColumnsTreeWidget.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.ColumnsTreeWidget.setStyleSheet("QTreeWidget {\n"
"    background-color: rgb(53, 50, 76);\n"
"    border-radius: 15px;\n"
"    color: rgb(238, 236, 255);/* Set your desired text color */\n"
"    font-family: Arial;\n"
"    font-size: 17px; /* Set your desired font size */\n"
"    padding: 5px; /* Set your desired padding */\n"
"    }\n"
"QHeaderView::section {\n"
"    background-color: rgb(53, 50, 76); /* Set your desired background color */\n"
"    color: rgb(238, 236, 255); /* Set your desired text color */\n"
"    font-family: Arial;\n"
"    font-weight:bold;\n"
"    font-size: 16px; /* Set your desired font size */\n"
"    border: none;\n"
"    padding: 5px; /* Set your desired padding */\n"
"    text-align: left; /* Set the alignment of the header text */\n"
"}")
        self.ColumnsTreeWidget.setAnimated(False)
        self.ColumnsTreeWidget.setObjectName("ColumnsTreeWidget")
        item_0 = QtWidgets.QTreeWidgetItem(self.ColumnsTreeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.ColumnsTreeWidget)
        self.verticalLayout_4.addWidget(self.ColumnsTreeWidget)
        self.horizontalLayout_3.addWidget(self.ColumnsWidget)
        self.widget_6 = QtWidgets.QWidget(self.widget_3)
        self.widget_6.setStyleSheet("")
        self.widget_6.setObjectName("widget_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_6)
        self.verticalLayout_5.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.SelectLabel = QtWidgets.QLabel(self.widget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SelectLabel.sizePolicy().hasHeightForWidth())
        self.SelectLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.SelectLabel.setFont(font)
        self.SelectLabel.setStyleSheet("QLabel{\n"
"    background-color: rgb(42, 38, 62);\n"
"    color: rgb(238, 236, 255);/* Set your desired text color */\n"
"    font-family: Arial;\n"
"    font-size: 20px; /* Set your desired font size */\n"
"    font-weight: bold;\n"
"    }")
        self.SelectLabel.setObjectName("SelectLabel")
        self.verticalLayout_5.addWidget(self.SelectLabel)
        self.SelectListWidget = QtWidgets.QListWidget(self.widget_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SelectListWidget.setFont(font)
        self.SelectListWidget.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.SelectListWidget.setStyleSheet("QListWidget{\n"
"    background-color: rgb(53, 50, 76);\n"
"    border-radius: 15px;\n"
"    }")
        self.SelectListWidget.setObjectName("SelectListWidget")
        self.verticalLayout_5.addWidget(self.SelectListWidget)
        self.horizontalLayout_3.addWidget(self.widget_6)
        self.horizontalLayout.addWidget(self.widget_3)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 8)
        self.verticalLayout_2.addWidget(self.BodyWidget)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 9)
        self.verticalLayout.addWidget(self.widget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.SideBarButton.setToolTip(_translate("MainWindow", "<html><head/><body><p>Open/Close SideBar</p></body></html>"))
        self.LoginButton.setToolTip(_translate("MainWindow", "<html><head/><body><p>Login</p></body></html>"))
        self.SaveSQLButton.setToolTip(_translate("MainWindow", "<html><head/><body><p>Save SQL</p></body></html>"))
        self.ReportsWindowButton.setToolTip(_translate("MainWindow", "<html><head/><body><p>Opens report repository window</p></body></html>"))
        self.QueryRunButton.setToolTip(_translate("MainWindow", "<html><head/><body><p>Opens report repository window</p></body></html>"))
        self.QueryAbortButton.setToolTip(_translate("MainWindow", "<html><head/><body><p>Opens report repository window</p></body></html>"))
        self.ThemeChangeButton.setToolTip(_translate("MainWindow", "<html><head/><body><p>Change theme color</p></body></html>"))
        self.NotificationBellButton.setToolTip(_translate("MainWindow", "<html><head/><body><p>See notifications</p></body></html>"))
        self.LogoutButton.setToolTip(_translate("MainWindow", "<html><head/><body><p>LogOut</p></body></html>"))
        self.HelpButton.setToolTip(_translate("MainWindow", "<html><head/><body><p>Help Manual</p></body></html>"))
        self.DBLabel.setText(_translate("MainWindow", ".        ."))
        self.SchemaLabel.setText(_translate("MainWindow", ".        ."))
        self.TableLabel.setText(_translate("MainWindow", ".        ."))
        self.TopRowsLabel.setText(_translate("MainWindow", " Limit:"))
        self.TopRowsLineEdit.setText(_translate("MainWindow", "1000000"))
        self.NullAsLabel.setText(_translate("MainWindow", " Null As:"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.UtilitiesPage), _translate("MainWindow", "Table / Utilities"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.StandardSQLPage), _translate("MainWindow", "Standard SQLs"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.UserSQLPage), _translate("MainWindow", "User SQLs"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.PublicSQLPage), _translate("MainWindow", "Public SQLs"))
        self.ColumnsLabel.setText(_translate("MainWindow", "Columns"))
        self.ColumnsTreeWidget.headerItem().setText(0, _translate("MainWindow", "Column"))
        self.ColumnsTreeWidget.headerItem().setText(1, _translate("MainWindow", "Field"))
        __sortingEnabled = self.ColumnsTreeWidget.isSortingEnabled()
        self.ColumnsTreeWidget.setSortingEnabled(False)
        self.ColumnsTreeWidget.topLevelItem(0).setText(0, _translate("MainWindow", "AUTH_CDE"))
        self.ColumnsTreeWidget.topLevelItem(0).setText(1, _translate("MainWindow", "F12"))
        self.ColumnsTreeWidget.topLevelItem(1).setText(0, _translate("MainWindow", "SETL_AMT"))
        self.ColumnsTreeWidget.topLevelItem(1).setText(1, _translate("MainWindow", "F11"))
        self.ColumnsTreeWidget.setSortingEnabled(__sortingEnabled)
        self.SelectLabel.setText(_translate("MainWindow", "Select"))
import resource_rc
